### ISSUE TITLE
Does Xcode 6.3.1 go ok with the rep?

### ISSUE THREAD

**Issue by tsuney** [hasegawa-tomoki/GourmetSearch#1]
グルメ情報アプリですが、 Xcode 6.3.1 for iOS8.3　上でトライしましたが、
Swiftバージョン？（as!問題）などでFailします。これはやはり、6.3.1との互換性の問題でしょうか。

**Comment by buiteke** [comment]
私もtsuneyさんと同じ環境でグルメ情報アプリにトライしましたが、同じくFailします。本を購入するのは私のようにiOSアプリ開発の初心者が多いと思うので、解決策を示していただけるとありがたいです。

**Comment by hasegawa-tomoki** [comment]
すみません、メッセージに気付いていませんでした。
そうですね。Xcode 6.3の Swift 1.2 の問題です。
コラムで対策を少し触れていますが他にもお問合せを頂いているので、6.3対応版ソースを準備中です。

**Comment by tsuney** [comment]
ありがとうございます！
